services:
  # 1. Base de Datos (Postgres)
  postgres:
    image: postgres:16-alpine
    container_name: postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: actividad_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/scripts:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d actividad_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Tu Aplicación Web (Next.js)
  app:
    build: .
    container_name: nextjs_reports_app
    ports:
      - "3000:3000"
    environment:
      # AQUÍ ESTÁ EL CAMBIO: Agregamos ?sslmode=disable al final
      DATABASE_URL: postgresql://reports_app_user_e:equipo_E_secure_pass_2025@postgres_container:5432/actividad_db?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: